### ISSUE TITLE
Introduce Project management proof

### ISSUE THREAD

**Issue by Aemilivs** [Aemilivs/2104-SC-BL-ICA-1#11]
Per ICA-1 requirement there should be a deliverable that documents our teamwork, capturing the final state of the project
and the communication that happened during the project via discussions on pull-requests and
others. The documentation is composed of a short description of the teams development process
(min 700 words and max 1500 words) and printscreens (can be delivered separately from the text
document or as part of it) from the final state of the project on GitHub. 

Should contain all the relevant pages, including, but not limited to:
* Open issues
* Closed issues
* Project dashboard
* Repository commit history
* Pull requests and their state

**Comment by h0nz1n** [comment]
Attaching the Project Management Proof document:
[Project Management Proof.docx](https://github.com/Aemilivs/2104-SC-BL-ICA-1/files/7576504/Project.Management.Proof.docx)

**Comment by h0nz1n** [comment]
Uploading Latex format of the document in PDF:
[project_management_proof.pdf](https://github.com/Aemilivs/2104-SC-BL-ICA-1/files/7577084/project_management_proof.pdf)
